#!/bin/bash

if [[ $(which php) && ${?} -gt 0 ]]; then
    echo "Could not find php binary."
    exit 1
fi

if [[ ! -d "vendor" ]]; then
    echo "Missing dependency directory..."

    read -rp "Do you want to install dependencies? [y/N]" yn
    case ${yn} in
      [Nn]* ) exit 1;;
    esac

    if [[ $(which composer) && ${?} -gt 0 ]]; then
      echo "Tried to solve this problem but composer binary could not be located, exiting."
      exit 1
    fi

    if [[ $(composer install --no-interaction --no-dev) -eq 0 ]]; then
      echo "Setup successful, please run gctl again"
    else
      echo "Installation failed, check logs above!"
      exit 1
    fi
fi

# Run application
php -f cli.php "$@"